export var TweenEasing = {
  quadIn: "quadIn",
  quadOut: "quadOut",
  quadInOut: "quadInOut",
  cubicIn: "cubicIn",
  cubicOut: "cubicOut",
  cubicInOut: "cubicInOut",
  quartIn: "quartIn",
  quartOut: "quartOut",
  quartInOut: "quartInOut",
  quintIn: "quintIn",
  quintOut: "quintOut",
  quintInOut: "quintInOut",
  sineIn: "sineIn",
  sineOut: "sineOut",
  sineInOut: "sineInOut",
  expoIn: "expoIn",
  expoOut: "expoOut",
  expoInOut: "expoInOut",
  circIn: "circIn",
  circOut: "circOut",
  circInOut: "circInOut",
  elasticIn: "elasticIn",
  elasticOut: "elasticOut",
  elasticInOut: "elasticInOut",
  backIn: "backIn",
  backOut: "backOut",
  backInOut: "backInOut",
  bounceIn: "bounceIn",
  bounceOut: "bounceOut",
  bounceInOut: "bounceInOut",
  smooth: "smooth",
  fade: "fade"
};
export enum TweenEasingEnum {
  quadIn = 0,
  quadOut = 1,
  quadInOut = 2,
  cubicIn = 3,
  cubicOut = 4,
  cubicInOut = 5,
  quartIn = 6,
  quartOut = 7,
  quartInOut = 8,
  quintIn = 9,
  quintOut = 10,
  quintInOut = 11,
  sineIn = 12,
  sineOut = 13,
  sineInOut = 14,
  expoIn = 15,
  expoOut = 16,
  expoInOut = 17,
  circIn = 18,
  circOut = 19,
  circInOut = 20,
  elasticIn = 21,
  elasticOut = 22,
  elasticInOut = 23,
  backIn = 24,
  backOut = 25,
  backInOut = 26,
  bounceIn = 27,
  bounceOut = 28,
  bounceInOut = 29,
  smooth = 30,
  fade = 31,
}