export var levelGuideData = {
  globalScale: 1,
  bottles: [[{
    id: 1,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [{
      color: 0,
      layer: 1,
      isQuestionMark: false
    }],
    bottleConfigType: 0,
    x: 346,
    y: 357,
    z: 0
  }, {
    id: 2,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [{
      color: 0,
      layer: 3,
      isQuestionMark: false
    }],
    bottleConfigType: 0,
    x: 222,
    y: 357,
    z: 0
  }], [{
    id: 3,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [{
      color: 3,
      layer: 2,
      isQuestionMark: false
    }],
    bottleConfigType: 0,
    x: 370,
    y: 350,
    z: 0
  }, {
    id: 4,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [{
      color: 0,
      layer: 2,
      isQuestionMark: false
    }],
    bottleConfigType: 0,
    x: 199,
    y: 350,
    z: 0
  }, {
    id: 5,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [{
      color: 0,
      layer: 2,
      isQuestionMark: false
    }, {
      color: 3,
      layer: 2,
      isQuestionMark: false
    }],
    bottleConfigType: 0,
    x: 285,
    y: 350,
    z: 0
  }], [{
    id: 6,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [{
      color: 3,
      layer: 2,
      isQuestionMark: false
    }, {
      color: 8,
      layer: 2,
      isQuestionMark: false
    }],
    bottleConfigType: 0,
    x: 328,
    y: 357,
    z: 0
  }, {
    id: 7,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [{
      color: 0,
      layer: 2,
      isQuestionMark: false
    }, {
      color: 3,
      layer: 2,
      isQuestionMark: false
    }],
    bottleConfigType: 0,
    x: 156,
    y: 357,
    z: 0
  }, {
    id: 8,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [{
      color: 8,
      layer: 2,
      isQuestionMark: false
    }, {
      color: 0,
      layer: 2,
      isQuestionMark: false
    }],
    bottleConfigType: 0,
    x: 242,
    y: 357,
    z: 0
  }, {
    id: 9,
    isLockBottleAD: false,
    occlusionUnlockNum: 0,
    targetColor: 0,
    fixedColor: 0,
    obstacleState: 0,
    waterDataList: [],
    bottleConfigType: 0,
    x: 414,
    y: 359,
    z: 0
  }]]
};